# @package task
name: G1

viewer:
  resolution: [1280, 720]
  lookat: [0., 0., 0.]
  eye: [4.0, 4.0, 4.0]

robot: 
  name: g1_29dof
terrain: plane

# common
num_envs: 4096
max_episode_length: 500

sim:
  step_dt: 0.02
  isaac_physics_dt: 0.005
  mujoco_physics_dt: 0.002

action:
  _target_: active_adaptation.envs.mdp.action.JointPosition
  action_scaling:
    waist_yaw_joint: 0.25
    waist_roll_joint: 0.25
    waist_pitch_joint: 0.25
    .*hip.*: 0.25
    .*knee.*: 0.25
    .*ankle.*: 0.25
    .*shoulder.*: 0.25
    .*elbow_joint: 0.25
  max_delay: 1
  alpha: [0.8, 1.0]

command: {}
observation: {}
reward: {}
randomization: {}
termination: {}