# @package task
name: G1Track

defaults:
  # see https://hydra.cc/docs/advanced/overriding_packages/
  - /task/G1/G1
  - _self_

flags: [""]

command:
  _target_: active_adaptation.envs.mdp.commands.motion_tracking.MotionTrackingCommand
  data_path: /home/elijah/Documents/projects/percep-loco/HV-dev/humanoidverse/data/motion_dataset/UnitreeG1/walk1_subject1-processed

observation:
  command:
    ref_motion_phase: {}
  policy:
    root_angvel_b:  {noise_std: 0.05}
    projected_gravity_b: {noise_std: 0.01}
    joint_pos_multistep: {steps: 16, noise_std: 0.01}
    joint_vel_multistep: {steps: 4, noise_std: 0.05}
    prev_actions:   {steps: 4}
  priv:
    ref_joint_pos_future: {}
    ref_joint_vel_future: {}
    diff_body_pos_future_b: {}
    diff_body_lin_vel_future_b: {}
    diff_body_ori_future_b: {}
    diff_body_ang_vel_future_b: {}
    applied_action:   {}
    root_linvel_b:    {}
    feet_pos_b:       {feet_names: .*ankle_roll_link}
    feet_vel_b:       {feet_names: .*ankle_roll_link}
    applied_torque:   {}
    cum_error:        {}

reward:
  # tracking:
  #   keypoint_tracking:     {weight: 2.0, sigma: 0.1, enabled: false}
  #   keypoint_tracking_product: {weight: 2.0, sigma: 0.1}
  #   keypoint_vel_tracking: {weight: 2.0, sigma: 0.5}
  #   root_pos_tracking:     {weight: 0.6, sigma: 0.25}
  #   root_ori_tracking:     {weight: 0.6, sigma: 0.15}
  #   root_vel_tracking:     {weight: 1.0, sigma: 0.25}
  #   joint_pos_tracking:    {weight: 0.6, sigma: 0.5}
  #   joint_vel_tracking:    {weight: 0.2, sigma: 0.5}
  # tracking_tight:
  #   keypoint_tracking:     {weight: 2.0, sigma: 0.02, enabled: false}
  #   keypoint_tracking_product: {weight: 2.0, sigma: 0.02}
  #   root_pos_tracking:     {weight: 0.6, sigma: 0.02}
  #   root_ori_tracking:     {weight: 0.6, sigma: 0.05}
  #   root_vel_tracking:     {weight: 1.0, sigma: 0.05}
  #   joint_pos_tracking:    {weight: 0.6, sigma: 0.05}
  #   joint_vel_tracking:    {weight: 0.2, sigma: 0.1}
  tracking:
    keypoint_pos_tracking_product: {weight: 1.0, sigma: 0.1}
    keypoint_ori_tracking_product: {weight: 1.0, sigma: 0.5}
    keypoint_lin_vel_tracking_product: {weight: 1.0, sigma: 0.5}
    keypoint_ang_vel_tracking_product: {weight: 1.0, sigma: 0.5, enabled: false}
    joint_pos_tracking_product:    {weight: 0.5, sigma: 0.5}
    joint_vel_tracking_product:    {weight: 0.5, sigma: 0.5}
  tracking_tight:
    keypoint_pos_tracking_product: {weight: 1.0, sigma: 0.02}
    keypoint_ori_tracking_product: {weight: 1.0, sigma: 0.05}
    keypoint_lin_vel_tracking_product: {weight: 1.0, sigma: 0.05}
    keypoint_ang_vel_tracking_product: {weight: 1.0, sigma: 0.05, enabled: false}
    joint_pos_tracking_product:    {weight: 0.5, sigma: 0.05}
    joint_vel_tracking_product:    {weight: 0.5, sigma: 0.05}
  loco:
    impact_force_l2:    {weight: 0.5, enabled: true, body_names: .*ankle_roll_link}
    feet_slip:          {weight: 1.0, tolerance: 0.05, enabled: true, body_names: .*ankle_roll_link}
    feet_swing_height:  {weight: 0.01, enabled: true, body_names: .*ankle_roll_link, target_height: 0.2}
    feet_air_time:      {weight: 3.0, enabled: true, body_names: [left_ankle_roll_link, right_ankle_roll_link], thres: 0.2}
    joint_vel_l2:       {weight: 5.0e-4, enabled: true, joint_names: .*}
    action_rate_l2:     {weight: 0.01, enabled: true}
    # feet_air_time_ref:      {weight: 10.0, enabled: true, body_names: [left_ankle_roll_link, right_ankle_roll_link], thres: 0.5}
    angvel_xy_l2:       {weight: 0.1, enabled: true, body_names: ["pelvis", "torso_link"]}

    feet_contact_count: {weight: 1.0, enabled: false, body_names: .*ankle_roll_link}


randomization: {}

termination:
  cum_error: {thres: 1.0, min_steps: 25}