# @package task

name: Test
task: Humanoid

defaults:
  # see https://hydra.cc/docs/advanced/overriding_packages/
  - /task/Track@_here_
  - override /task/action@action: null
  - _self_

payload: false

action:
  _target_: active_adaptation.envs.mdp.action.JointPosition
  action_scaling: {.*: 0.5}
  max_delay: 1
  alpha: [0.5, 1.0]

command:
  _target_: active_adaptation.envs.mdp.MotionLib
  motion_clip: "scripts/data/amass_all.pkl"
  joint_names: ""
  
observation:
  policy:
    root_quat_w:
    root_angvel_b:        {noise_std: 0.05}
    projected_gravity_b:  {noise_std: 0.01}
    joint_pos:            {noise_std: 0.05}
    joint_vel:            {noise_std: 0.2}
    body_pos:             {body_names: [left_hip_pitch_link, left_knee_link, left_ankle_roll_link, 
                                        right_hip_pitch_link, right_knee_link, right_ankle_roll_link,
                                        left_shoulder_roll_link, left_elbow_pitch_link, left_zero_link, 
                                        right_shoulder_roll_link, right_elbow_pitch_link, right_zero_link], 
                                        yaw_only: false}
    prev_actions:         {steps: 1}
  priv:
    applied_action:   {}
    root_linvel_b:    {yaw_only: true}
    body_vel:         {body_names: [left_hip_pitch_link, left_knee_link, left_ankle_roll_link, 
                                        right_hip_pitch_link, right_knee_link, right_ankle_roll_link,
                                        left_shoulder_roll_link, left_elbow_pitch_link, left_zero_link, 
                                        right_shoulder_roll_link, right_elbow_pitch_link, right_zero_link], 
                                        yaw_only: false}
    applied_torques:  {actuator_name: legs}
    contact_indicator: {body_names: [".*ankle_roll_link"], timing: false}
    joint_forces:     {}
    jacobians:        {body_names: [torso_link, .*palm_link, .*ankle_roll_link]}

reward:
  loco:

    survival:           {weight: 1.0, enabled: true}

    energy_l1:          {weight: 5.0e-4, enabled: true}
    joint_acc_l2:       {weight: 1.0e-8, enabled: true}
    joint_vel_l2:       {weight: 0.002, enabled: true, joint_names: .*}
    joint_torques_l2:   {weight: 1.0e-5, enabled: true, joint_names: .*}
    action_rate_l2:     {weight: 0.02, enabled: true}
    action_rate2_l2:    {weight: 0.01, enabled: true}

randomization:
  push:     {body_names: ["torso_link", "pelvis"], force_range: [0.0, 0.1]}
  perturb_body_mass:
    .*: [0.9, 1.1]
  perturb_body_materials:
    body_names: ".*ankle_roll_link"
    static_friction_range: [0.6, 4.0]
    dynamic_friction_range: [0.6, 4.0]
    restitution_range: [0.0, 0.2]
  motor_params:
    actuator_name:    legs
    stiffness_range:  [0.7, 1.0]
    damping_range:    [0.7, 1.0]
  reset_joint_states_uniform:
    pos_ranges:
      .*: [-0.3, 0.3]
    rel: true

termination:
  root_deviation: {max_distance: 0.5}
